# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 15:11
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blobs', '0002_blobmeta'),
        ('sql_accessors', '0061_blobmeta_sql_forms'),
    ]

    operations = []
